# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cenacle' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Cenacle
  pod 'Firebase/Core', '~> 5.11.0'
  pod 'Firebase/Storage', '~> 5.11.0'
  pod 'GoogleAppMeasurement', '~> 5.3.0'
  pod 'Firebase/Firestore', '~> 5.11.0'
  pod 'Firebase/Auth', '~> 5.11.0'

  target 'Cenacle-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
#    pod 'RNFS', :path => '../node_modules/react-native-fs'
#
#    pod 'react-native-calendar-events', :path => '../node_modules/react-native-calendar-events'
#
#    pod 'RNAudioStreaming', :path => '../node_modules/react-native-audio-streaming'

    pod 'react-native-video', :path => '../node_modules/react-native-video'

    pod 'react-native-track-player', :path => '../node_modules/react-native-track-player'


  end

  target 'CenacleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Cenacle-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Cenacle-tvOS

end
