# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Cenacle' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#  use_frameworks!
#  use_modular_headers!

  # Pods for Cenacle
  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Storage', '~> 5.15.0'
  pod 'Firebase/Firestore', '~> 5.15.0'
  pod 'Firebase/Auth', '~> 5.15.0'
  pod 'Firebase/Messaging', '~> 5.15.0'
  
#  pod 'GoogleAppMeasurement', '~> 5.3.0'
  

  target 'Cenacle-tvOSTests' do
    inherit! :search_paths
    # Pods for testing



  end

  target 'CenacleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Cenacle-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Cenacle-tvOS

end
