import BibleParts from './parts'

const BibleLink = { label: 'Genèse',
  value: 'Gen',
  ord: '1',
  chapters: '50',
  gen: 'Genèse',
  exod: 'Exode',
  lev: 'Lévitique',
  num: 'Nombres',
  deut: 'Deutéronome',
  josh: 'Josué',
  judg: 'Juges',
  ruth: 'Ruth',
  '1sam': '1 Samuel',
  '2sam': '2 Samuel',
  '1kgs': '1 Rois',
  '2kgs': '2 Rois',
  '1chr': '1 Chroniques',
  '2chr': '2 Chroniques',
  ezra: 'Esdras',
  neh: 'Néhémie',
  esth: 'Esther',
  job: 'Job',
  ps: 'Psaumes',
  prov: 'Proverbes',
  eccl: 'Ecclésiaste',
  song: 'Cantique',
  isa: 'Ésaïe',
  jer: 'Jérémie',
  lam: 'Lamentations',
  ezek: 'Ézékiel',
  dan: 'Daniel',
  hos: 'Osée',
  joel: 'Joël',
  amos: 'Amos',
  obad: 'Abdias',
  jonah: 'Jonas',
  mic: 'Michée',
  nah: 'Nahum',
  hab: 'Habacuc',
  zeph: 'Sophonie',
  hag: 'Aggée',
  zech: 'Zacharie',
  mal: 'Malachie',
  matt: 'Matthieu',
  mark: 'Marc',
  luke: 'Luc',
  john: 'Jean',
  acts: 'Actes',
  rom: 'Romains',
  '1cor': '1 Corinthiens',
  '2cor': '2 Corinthiens',
  gal: 'Galates',
  eph: 'Éphésiens',
  phil: 'Philippiens',
  col: 'Colossiens',
  '1thess': '1 Thessaloniciens',
  '2thess': '2 Thessaloniciens',
  '1tim': '1 Timothée',
  '2tim': '2 Timothée',
  titus: 'Tite',
  phlm: 'Philémon',
  heb: 'Hébreux',
  jas: 'Jacques',
  '1pet': '1 Pierre',
  '2pet': '2 Pierre',
  '1john': '1 Jean',
  '2john': '2 Jean',
  '3john': '3 Jean',
  jude: 'Jude',
  rev: 'Apocalypse' }

const BibleLinkId = { gen: 'fra-LSG:Gen',
exod: 'fra-LSG:Exod',
lev: 'fra-LSG:Lev',
num: 'fra-LSG:Num',
deut: 'fra-LSG:Deut',
josh: 'fra-LSG:Josh',
judg: 'fra-LSG:Judg',
ruth: 'fra-LSG:Ruth',
'1sam': 'fra-LSG:1Sam',
'2sam': 'fra-LSG:2Sam',
'1kgs': 'fra-LSG:1Kgs',
'2kgs': 'fra-LSG:2Kgs',
'1chr': 'fra-LSG:1Chr',
'2chr': 'fra-LSG:2Chr',
ezra: 'fra-LSG:Ezra',
neh: 'fra-LSG:Neh',
esth: 'fra-LSG:Esth',
job: 'fra-LSG:Job',
ps: 'fra-LSG:Ps',
prov: 'fra-LSG:Prov',
eccl: 'fra-LSG:Eccl',
song: 'fra-LSG:Song',
isa: 'fra-LSG:Isa',
jer: 'fra-LSG:Jer',
lam: 'fra-LSG:Lam',
ezek: 'fra-LSG:Ezek',
dan: 'fra-LSG:Dan',
hos: 'fra-LSG:Hos',
joel: 'fra-LSG:Joel',
amos: 'fra-LSG:Amos',
obad: 'fra-LSG:Obad',
jonah: 'fra-LSG:Jonah',
mic: 'fra-LSG:Mic',
nah: 'fra-LSG:Nah',
hab: 'fra-LSG:Hab',
zeph: 'fra-LSG:Zeph',
hag: 'fra-LSG:Hag',
zech: 'fra-LSG:Zech',
mal: 'fra-LSG:Mal',
matt: 'fra-LSG:Matt',
mark: 'fra-LSG:Mark',
luke: 'fra-LSG:Luke',
john: 'fra-LSG:John',
acts: 'fra-LSG:Acts',
rom: 'fra-LSG:Rom',
'1cor': 'fra-LSG:1Cor',
'2cor': 'fra-LSG:2Cor',
gal: 'fra-LSG:Gal',
eph: 'fra-LSG:Eph',
phil: 'fra-LSG:Phil',
col: 'fra-LSG:Col',
'1thess': 'fra-LSG:1Thess',
'2thess': 'fra-LSG:2Thess',
'1tim': 'fra-LSG:1Tim',
'2tim': 'fra-LSG:2Tim',
titus: 'fra-LSG:Titus',
phlm: 'fra-LSG:Phlm',
heb: 'fra-LSG:Heb',
jas: 'fra-LSG:Jas',
'1pet': 'fra-LSG:1Pet',
'2pet': 'fra-LSG:2Pet',
'1john': 'fra-LSG:1John',
'2john': 'fra-LSG:2John',
'3john': 'fra-LSG:3John',
jude: 'fra-LSG:Jude',
rev: 'fra-LSG:Rev' }
export {
  BibleParts,
  BibleLink,
  BibleLinkId
}

